# Generated by Django 5.2.1 on 2025-05-26 07:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALaCarteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addons_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submenu_input', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], max_length=20)),
                ('address', models.TextField()),
                ('unit', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('a_la_carte', 'A La Carte'), ('bundled', 'Bundled')], max_length=20)),
                ('bundle_group', models.CharField(blank=True, max_length=255, null=True)),
                ('bundle_item', models.CharField(blank=True, max_length=255, null=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupancy_vacant', models.BooleanField(default=False)),
                ('occupancy_occupied', models.BooleanField(default=False)),
                ('access_lock_box', models.BooleanField(default=False)),
                ('lock_box_code', models.CharField(blank=True, max_length=50, null=True)),
                ('lock_box_location', models.TextField(blank=True, null=True)),
                ('access_app_lock_box', models.BooleanField(default=False)),
                ('access_meet_contact', models.BooleanField(default=False)),
                ('access_hidden_key', models.BooleanField(default=False)),
                ('hidden_key_directions', models.TextField(blank=True, null=True)),
                ('access_community_access', models.BooleanField(default=False)),
                ('community_access_instructions', models.TextField(blank=True, null=True)),
                ('access_door_code', models.BooleanField(default=False)),
                ('door_code_value', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_datetime', models.DateTimeField(blank=True, null=True)),
                ('contact_name_sched', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone_sched', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email_sched', models.EmailField(blank=True, max_length=254, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ALaCarteAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='stripe_payment.alacarteservice')),
            ],
        ),
        migrations.CreateModel(
            name='ALaCarteSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('option_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='stripe_payment.alacarteservice')),
            ],
        ),
        migrations.AddField(
            model_name='alacarteservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_la_carte_services', to='stripe_payment.order'),
        ),
    ]
