# Generated by Django 5.2.1 on 2025-05-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alacarteaddon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
