# Generated by Django 5.2.1 on 2025-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
