# Generated by Django 5.2.1 on 2025-05-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0004_alter_order_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alacartesubmenu',
            name='option_price',
        ),
    ]
