# Generated by Django 5.2.1 on 2025-05-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0005_remove_alacartesubmenu_option_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bundle_price',
            new_name='total_price',
        ),
    ]
