# Generated by Django 5.2.1 on 2025-05-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0006_rename_bundle_price_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('payment_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_subtotal', models.IntegerField()),
                ('amount_total', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=100, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('captured', models.BooleanField(default=False)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=2, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('network_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
