# Generated by Django 5.2.1 on 2025-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0007_checkoutsession_stripecharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_order_id',
            new_name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
