# Generated by Django 5.2.1 on 2025-05-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0008_rename_stripe_order_id_order_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_intent_id',
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='session_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
