# Generated by Django 5.2.1 on 2025-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0009_remove_checkoutsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharge',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
    ]
