# Generated by Django 5.2.1 on 2025-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0011_invoice_order_city_order_postal_code_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
