# Generated by Django 5.2.1 on 2025-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0012_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
