# Generated by Django 5.2.1 on 2025-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0014_notaryclientcompany_notaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alacarteservice',
            name='reduced_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
