# Generated by Django 5.2.1 on 2025-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0016_alacartesubmenu_prompt_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEventLog',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
