# Generated by Django 5.2.1 on 2025-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0017_stripewebhookeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sp_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
