# Generated by Django 5.2.1 on 2025-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0019_rename_contact_name_sched_order_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alacarteaddon',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notaryclientcompany',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
