# Generated by Django 5.2.1 on 2025-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0020_alacarteaddon_key_alter_notaryclientcompany_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaryclientcompany',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='notaryclientcompany',
            name='attr',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
