# Generated by Django 5.2.1 on 2025-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0021_alter_notaryclientcompany_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ownwer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stripewebhookeventlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripewebhookeventlog',
            name='json_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripewebhookeventlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
