# Generated by Django 5.2.1 on 2025-07-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0022_order_company_id_order_ownwer_id_order_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ownwer_id',
            new_name='owner_id',
        ),
    ]
