# Generated by Django 5.2.1 on 2025-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0025_coupon_name_order_coupon_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone_sched_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('landline', 'Landline')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('landline', 'Landline')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cosigner_phone_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('landline', 'Landline')], max_length=20, null=True),
        ),
    ]
