# Generated by Django 5.2.1 on 2025-09-20 08:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0026_order_contact_phone_sched_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alacartesubmenu',
            name='service',
        ),
        migrations.RenameField(
            model_name='alacarteservice',
            old_name='description',
            new_name='form_description',
        ),
        migrations.RenameField(
            model_name='alacarteservice',
            old_name='name',
            new_name='form_title',
        ),
        migrations.RenameField(
            model_name='alacarteservice',
            old_name='prompt',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='alacarteservice',
            name='addons_price',
        ),
        migrations.RemoveField(
            model_name='alacarteservice',
            name='key',
        ),
        migrations.RemoveField(
            model_name='alacarteservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='alacarteservice',
            name='reduced_names',
        ),
        migrations.RemoveField(
            model_name='alacarteservice',
            name='submenu_input',
        ),
        migrations.RemoveField(
            model_name='alacarteservice',
            name='total_price',
        ),
        migrations.AddField(
            model_name='alacarteservice',
            name='service_id',
            field=models.CharField(default='sdfg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alacarteservice',
            name='title',
            field=models.CharField(default='sdfg', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ALaCarteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protection_invalid', models.BooleanField(default=False)),
                ('options_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('counter', 'Counter'), ('none', 'None'), ('mixed', 'Mixed')], default='none', max_length=50)),
                ('minimum_required', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stripe_payment.alacarteservice')),
            ],
        ),
        migrations.CreateModel(
            name='ALaCarteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stripe_payment.alacarteitem')),
            ],
        ),
        migrations.CreateModel(
            name='ALaCarteSubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu_item_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('counter', 'Counter'), ('checkbox', 'Checkbox')], default='counter', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_items', to='stripe_payment.alacarteitem')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='stripe_payment.order')),
            ],
        ),
        migrations.DeleteModel(
            name='ALaCarteAddOn',
        ),
        migrations.DeleteModel(
            name='ALaCarteSubMenu',
        ),
    ]
