# Generated by Django 5.2.1 on 2025-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0027_remove_alacartesubmenu_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_protection',
            field=models.BooleanField(default=False),
        ),
    ]
