# Generated by Django 5.2.1 on 2025-09-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0029_order_discount_amount_order_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bundle_group',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bundle_item',
        ),
    ]
