# Generated by Django 5.2.1 on 2025-09-26 15:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0030_remove_order_bundle_group_remove_order_bundle_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_protection_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
