# Generated by Django 5.2.1 on 2025-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0031_order_order_protection_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='occupancy_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
