# Generated by Django 5.2.7 on 2025-10-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0032_order_occupancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('a_la_carte', 'A La Carte'), ('bundled', 'Bundled'), ('mixed', 'Mixed')], max_length=20),
        ),
    ]
