# Generated by Django 5.2.7 on 2025-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0033_alter_order_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_team_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
