# Generated by Django 5.2.7 on 2025-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0034_order_client_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryuser',
            name='page_visited',
            field=models.BooleanField(default=False),
        ),
    ]
