# Generated by Django 5.2.7 on 2025-11-19 21:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0035_notaryuser_page_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_protection_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
