# Generated by Django 5.2.7 on 2025-11-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0036_alter_order_order_protection_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_protection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
