# Generated by Django 5.2.7 on 2025-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0037_alter_order_order_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alacarteitem',
            name='options_type',
            field=models.CharField(blank=True, choices=[('checkbox', 'Checkbox'), ('counter', 'Counter'), ('none', 'None'), ('mixed', 'Mixed')], max_length=50, null=True),
        ),
    ]
