# Generated by Django 5.2.7 on 2025-12-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0029_termsofconditions_version_id'),
        ('stripe_payment', '0038_alter_alacarteitem_options_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryuser',
            name='last_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaryuser',
            name='signed_terms',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='order_page.termsofconditions'),
        ),
    ]
