# Generated by Django 5.2.7 on 2025-12-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0041_alacarteitemmodaloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryclientcompany',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notaryclientcompany',
            name='stripe_default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
