# Generated by Django 5.2.7 on 2025-12-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0042_notaryclientcompany_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaryuser',
            name='email_unverified',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
