# Generated by Django 5.2.7 on 2025-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0043_alter_notaryuser_email_unverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notary_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
