# Generated by Django 5.2.7 on 2025-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0044_order_notary_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
