# Generated by Django 5.2.7 on 2025-12-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0045_order_preferred_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALaCarteItemDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='stripe_payment.alacarteitem')),
            ],
        ),
    ]
