# Generated by Django 5.2.7 on 2026-01-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0046_alacarteitemdisclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotaryCompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('companies', models.ManyToManyField(related_name='groups', to='stripe_payment.notaryclientcompany')),
            ],
        ),
    ]
