# Generated by Django 5.2.7 on 2026-01-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0047_notaryuser_is_admin_notarycompanygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notaryuser',
            name='stripe_default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
