# Generated by Django 5.2.7 on 2026-01-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0048_notaryuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status_emails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
