# Generated by Django 5.2.7 on 2026-01-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0049_order_order_status_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point_of_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
