# Generated by Django 5.2.7 on 2026-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0050_order_point_of_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_first_name_resched',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_last_name_resched',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone_resched',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rescheduling_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
