# Generated by Django 5.2.7 on 2026-01-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0051_order_appointment_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaryuser',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='notaryuser',
            name='stripe_default_payment_method',
        ),
    ]
