# Generated by Django 5.2.7 on 2026-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0052_remove_notaryuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_lock_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
