# Generated by Django 5.2.10 on 2026-02-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0053_order_app_lock_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
