# Generated by Django 5.2.11 on 2026-02-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0054_order_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
