# Generated by Django 5.2.11 on 2026-02-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0055_order_number_of_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_external_odr',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Is External Order from Version 2 App', verbose_name='Is External Order'),
        ),
    ]
