# Generated by Django 5.2.11 on 2026-04-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0037_formitem_min_lead_time'),
        ('stripe_payment', '0056_order_is_external_odr'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryuser',
            name='typeform_partner_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notary_users', to='order_page.typeformpartnermapping'),
        ),
    ]
