# Generated by Django 5.2.11 on 2026-04-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0057_notaryuser_typeform_partner_mapping'),
        ('tolt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryuser',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notary_users', to='tolt.partner'),
        ),
    ]
