# Generated by Django 5.2.11 on 2026-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0058_notaryuser_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaryclientcompany',
            name='type',
            field=models.CharField(default='client', max_length=50),
        ),
    ]
