# Generated by Django 5.2.11 on 2026-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom JSON headers to include in the webhook request.'),
        ),
    ]
