# Generated by Django 5.2.1 on 2025-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='Brearer', max_length=100)),
                ('expires_at', models.DateField()),
                ('refresh_token', models.TextField()),
                ('scope', models.TextField()),
                ('userType', models.CharField(max_length=100)),
                ('companyId', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('LocationId', models.CharField(max_length=100, unique=True)),
                ('userId', models.CharField(max_length=100)),
            ],
        ),
    ]
