# Generated by Django 5.2.11 on 2026-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=50)),
                ('field_key', models.CharField(db_index=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('data_type', models.CharField(max_length=50)),
                ('parent_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
