# Generated by Django 5.2.6 on 2025-10-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('program_id', models.CharField(blank=True, max_length=64, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=64, null=True)),
                ('group_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payout_method', models.CharField(blank=True, max_length=64, null=True)),
                ('payout_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tolt_partner',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('param', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('program_id', models.CharField(blank=True, max_length=64, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=64, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='tolt.partner')),
            ],
            options={
                'db_table': 'tolt_link',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('program_id', models.CharField(blank=True, max_length=64, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=64, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tolt.partner')),
            ],
            options={
                'db_table': 'tolt_customer',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_type', models.CharField(blank=True, max_length=64, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=64, null=True)),
                ('click_id', models.CharField(blank=True, max_length=64, null=True)),
                ('product_id', models.CharField(blank=True, max_length=64, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('interval', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('program_id', models.CharField(blank=True, max_length=64, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tolt.customer')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tolt.partner')),
            ],
            options={
                'db_table': 'tolt_transaction',
            },
        ),
    ]
