"""
Django settings for dj_IBstripe project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from celery.schedules import crontab
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dyci7ysrl)@q*oiq@(=0m)%_7)(_)2o6y-(wi$zmm6^2wz@_bu'

SITE_ID = 1
SECRET_KEY = config('SECRET_KEY')
CLIENT_ID = config('CLIENT_ID')
CLIENT_SECRET = config('CLIENT_SECRET')
SCOPES = config('SCOPES')
REDIRECT_URI = config('REDIRECT_URI')


STRIPE_TEST= not (str(config('STRIPE_LIVE')).lower() == 'true') if config('STRIPE_LIVE') else True

if STRIPE_TEST:
    
    STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY_TEST')
    STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY_TEST')
else: 
    STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
    STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')

NOTARY_TEST = False
if NOTARY_TEST:
    NOTARY_API_KEY = config('NOTARY_TEST_API_KEY')
else:
    NOTARY_API_KEY = config('NOTARY_LIVE_API_KEY')

DEBUG = True

ALLOWED_HOSTS = ['go.investorbootz.com','127.0.0.1','localhost', '37d5165a4f2b.ngrok-free.app']

CORS_ALLOWED_ORIGINS = ['http://localhost:3000','http://localhost:5173','https://go.investorbootz.com']

CSRF_TRUSTED_ORIGINS = ['http://localhost:3000','http://localhost:5173','https://go.investorbootz.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_filters',
    'corsheaders',
    'django_summernote',
    'adminsortable2',
    'core',
    'stripe_payment',
    'order_page',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dj_IBstripe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dj_IBstripe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if config('DB', default="") == 'psql':
    STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # global static/
    ]
    DATABASES = {
            'default': {
                'ENGINE': config('DB_ENGINE'),
                'NAME': config('DB_NAME'),
                'HOST': config('DB_HOST'),
                'USER': config('DB_USER'),
                'PASSWORD': config('DB_PASSWORD'),
                'port': config('DB_PORT')
            }
        } 
else:
    STATIC_ROOT =  BASE_DIR / "static"
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),  # global static/
# ]
# STATIC_ROOT =  BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CELERY_BEAT_SCHEDULE = {
    'example_task': {
        'task': 'stripe_payment.tasks.example_task',
        'schedule': crontab(hour=0, minute=0),
        'args': (),
    },
    # 'sample_beat_task': {
    #     'task': 'stripe_payment.tasks.sample_beat_task',
    #     # 'schedule': crontab(second='*/5'),  
    #     # Runs every 5 seconds
    #     'schedule': 5,
    #     'args': (),
    # },
    'pull_clients': {
        'task': 'stripe_payment.tasks.pull_clients',
        'schedule':  crontab(hour=0, minute=0),
        'args': (),
    },
}

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

SUMMERNOTE_CONFIG = {
    # Disable all file/image uploads
    'disable_upload': True,

    # Optional: make it lightweight
    'summernote': {
        'width': '750px',
        'height': '600px',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'strikethrough', 'clear']], 
             ['fontsize', ['fontsize']],
            ['para', ['ul', 'ol', 'paragraph',]],
            ['format', ['p', 'blockquote', ]],
            ['misc', ['undo', 'redo']],
             ['view', ['codeview']],
             ['styltags',['styleTags']]
             
        ],
              'styleTags': [
            'p', 'blockquote',
            'h1', 'h2', 'h3', 'h4', 'h5', 'h6'
        ],
    },
    # 'iframe': False,

    # Optional: clean up HTML automatically
    'cleaner': {
        'allow_tags': {
            'p', 'br', 'blockquote',
            'ul', 'ol', 'li',
            'b', 'i', 'u', 'em', 'strong',
            'h1', 'h2', 'h3', 'h4', 'h5', 'h6'
        },
    },
}
