# Generated by Django 5.2.7 on 2025-10-24 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeformForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('endings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TypeformField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=50)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('field_type', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='order_page.typeformform')),
            ],
        ),
        migrations.CreateModel(
            name='TypeformResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('landed_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('hidden', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='order_page.typeformform')),
            ],
        ),
        migrations.CreateModel(
            name='TypeformAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(max_length=50)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='order_page.typeformfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='order_page.typeformresponse')),
            ],
        ),
        migrations.AddIndex(
            model_name='typeformfield',
            index=models.Index(fields=['field_id'], name='order_page__field_i_7caa57_idx'),
        ),
        migrations.AddIndex(
            model_name='typeformfield',
            index=models.Index(fields=['ref'], name='order_page__ref_30c196_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typeformfield',
            unique_together={('form', 'field_id')},
        ),
        migrations.AddIndex(
            model_name='typeformresponse',
            index=models.Index(fields=['form'], name='order_page__form_id_452f38_idx'),
        ),
        migrations.AddIndex(
            model_name='typeformresponse',
            index=models.Index(fields=['submitted_at'], name='order_page__submitt_b4f864_idx'),
        ),
        migrations.AddIndex(
            model_name='typeformanswer',
            index=models.Index(fields=['field'], name='order_page__field_i_7ab0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='typeformanswer',
            index=models.Index(fields=['response'], name='order_page__respons_202fe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typeformanswer',
            unique_together={('response', 'field')},
        ),
    ]
