# Generated by Django 5.2.7 on 2025-11-04 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0002_typeformform_typeformfield_typeformresponse_and_more'),
        ('stripe_payment', '0034_order_client_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('subheader', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protection_invalid', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=512, null=True)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('subheader_html', models.TextField(blank=True, null=True)),
                ('order_protection', models.BooleanField(default=False)),
                ('order_protection_disabled', models.BooleanField(default=False)),
                ('order_protection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_protection_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='info', help_text="e.g., 'info', 'warning'", max_length=50)),
                ('message', models.TextField(help_text='Disclosure or information message to show')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='order_page.individualservice')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='checkbox', max_length=50)),
                ('minimum_required', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='order_page.formitem')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_page.optiongroup')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='individualservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='order_page.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='order_page.individualservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModalOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('each_item', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(default='text', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_options', to='order_page.serviceform')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='formitem',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_page.serviceform'),
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='mixed', max_length=50)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='order_page.serviceform')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_page.submenu')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmenuPriceChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Submenu key, e.g. 'pages11_39'", max_length=100)),
                ('change_type', models.CharField(choices=[('add', 'Add'), ('multiple', 'Multiple')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_price_changes', to='order_page.formitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='order_page.bundlegroup')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceVariance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Version or variance name, e.g. 'Fall 2025 Edition', 'Company One Special'.", max_length=255)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Numeric version number.')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this variance is the default fallback for all clients.')),
                ('is_active', models.BooleanField(default=False, help_text='Mark this variance as currently active.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('bundle_group', models.ForeignKey(help_text='Associated bundle group this version applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='order_page.bundlegroup')),
                ('clients', models.ManyToManyField(blank=True, help_text='Clients that use this custom variance instead of the default.', related_name='service_variances', to='stripe_payment.notaryclientcompany')),
                ('service_category', models.ForeignKey(help_text='Associated service category this version applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='order_page.servicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('service_category', 'bundle_group', 'version_number')},
            },
        ),
    ]
