# Generated by Django 5.2.7 on 2025-11-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0003_bundlegroup_formitem_individualservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualservice',
            name='category',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Select the individual services that belong to this category.', related_name='categories', to='order_page.individualservice'),
        ),
    ]
