# Generated by Django 5.2.7 on 2025-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0004_remove_individualservice_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicevariance',
            unique_together={('name', 'version_number')},
        ),
        migrations.RemoveField(
            model_name='servicevariance',
            name='bundle_group',
        ),
        migrations.AddField(
            model_name='servicevariance',
            name='bundle_group',
            field=models.ManyToManyField(help_text='Associated bundle group this version applies to.', related_name='variances', to='order_page.bundlegroup'),
        ),
    ]
