# Generated by Django 5.2.7 on 2025-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0005_alter_servicevariance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualservice',
            name='order_protection_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percent'), ('fixed', 'Fixed')], help_text='Type of order protection applied (percent or fixed).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individualservice',
            name='order_protection_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The numeric value for order protection.', max_digits=10, null=True),
        ),
    ]
