# Generated by Django 5.2.7 on 2025-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0006_alter_individualservice_order_protection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualservice',
            name='slug',
        ),
        migrations.AddField(
            model_name='individualservice',
            name='service_id',
            field=models.CharField(default='define', max_length=100),
            preserve_default=False,
        ),
    ]
