# Generated by Django 5.2.7 on 2025-11-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0007_remove_individualservice_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formitem',
            name='form',
        ),
        migrations.RemoveField(
            model_name='modaloption',
            name='form',
        ),
        migrations.RemoveField(
            model_name='optiongroup',
            name='form_item',
        ),
        migrations.RemoveField(
            model_name='optionitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='serviceform',
            name='service',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='form',
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='submenupricechange',
            name='form_item',
        ),
        migrations.AddField(
            model_name='formitem',
            name='option_group',
            field=models.OneToOneField(blank=True, help_text='The group of selectable options linked to this form item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_item', to='order_page.optiongroup'),
        ),
        migrations.AddField(
            model_name='individualservice',
            name='form_ref',
            field=models.OneToOneField(blank=True, help_text='Link to the service form directly (reverse OneToOne).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_service', to='order_page.serviceform'),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Select one or more options that belong to this group.', related_name='groups', to='order_page.optionitem'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Select one or more form items for this form.', related_name='forms', to='order_page.formitem'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='modal_options',
            field=models.ManyToManyField(blank=True, help_text="Attach one or more modal options (e.g., 'Lockbox Code', 'Signer Name').", related_name='forms', to='order_page.modaloption'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='submenus',
            field=models.ManyToManyField(blank=True, help_text='Attach one or more submenus to this form.', related_name='forms', to='order_page.submenu'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Select one or more items to include in this submenu.', related_name='submenus', to='order_page.submenuitem'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='price_changes',
            field=models.ManyToManyField(blank=True, help_text='Optional price modifications linked to this submenu item.', related_name='submenu_items', to='order_page.submenupricechange'),
        ),
        migrations.AlterField(
            model_name='modaloption',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date')], default='text', help_text='Type of input field rendered in frontend.', max_length=50),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkbox')], default='checkbox', help_text='Type of option selection control.', max_length=50),
        ),
    ]
