# Generated by Django 5.2.7 on 2025-11-06 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0008_remove_formitem_form_remove_modaloption_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleOptionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio'), ('dropdown', 'Dropdown')], default='checkbox', help_text='Type of option selection control.', max_length=50)),
                ('minimum_required', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleOptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('price_add', models.DecimalField(blank=True, decimal_places=2, help_text='Additional price to add when this option is selected.', max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='optiongroup',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='optiongroup',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='bundle',
            name='option_groups',
            field=models.ManyToManyField(blank=True, help_text='Attach one or more option groups to this bundle.', related_name='bundles', to='order_page.bundleoptiongroup'),
        ),
        migrations.AddField(
            model_name='bundleoptiongroup',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Select one or more items that belong to this option group.', related_name='option_groups', to='order_page.bundleoptionitem'),
        ),
    ]
