# Generated by Django 5.2.7 on 2025-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0009_bundleoptiongroup_bundleoptionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariance',
            name='bundle_order_protection_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percent'), ('fixed', 'Fixed')], help_text='Type of order protection applied (percent or fixed).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicevariance',
            name='bundle_order_protection_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The numeric value for order protection.', max_digits=10, null=True),
        ),
    ]
