# Generated by Django 5.2.7 on 2025-11-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0010_servicevariance_bundle_order_protection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionitem',
            name='price_type',
            field=models.CharField(choices=[('priceAdd', 'Addition'), ('priceChange', 'Warning')], default='priceChange', help_text='Price altering behavior', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionitem',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='disclosure',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', help_text='Text color variations', max_length=50),
        ),
        migrations.AlterField(
            model_name='individualservice',
            name='form_ref',
            field=models.OneToOneField(blank=True, help_text='Choose or create Service Items set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_service', to='order_page.serviceform', verbose_name='Service Item set'),
        ),
        migrations.AlterField(
            model_name='individualservice',
            name='service_id',
            field=models.CharField(help_text='Make this short as possible, This will be used in combined product name in NotaryDash.', max_length=100),
        ),
        migrations.AlterField(
            model_name='individualservice',
            name='subheader_html',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-Header'),
        ),
        migrations.AlterField(
            model_name='servicevariance',
            name='service_category',
            field=models.ForeignKey(help_text='Associated service category this version applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='order_page.servicecategory', verbose_name='Individual service variance'),
        ),
    ]
