# Generated by Django 5.2.7 on 2025-11-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0011_optionitem_price_type_optionitem_price_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionitem',
            name='price_change',
        ),
        migrations.AlterField(
            model_name='optionitem',
            name='price_type',
            field=models.CharField(choices=[('priceAdd', 'Addition'), ('priceChange', 'Change Into')], help_text='Price altering behavior', max_length=15),
        ),
    ]
