# Generated by Django 5.2.7 on 2025-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0012_remove_optionitem_price_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionitem',
            name='value',
            field=models.BooleanField(default=False, verbose_name='Default Check'),
        ),
    ]
