# Generated by Django 5.2.7 on 2025-11-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0013_alter_optionitem_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenupricechange',
            options={'ordering': ['form_item', 'submenu_item']},
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='price_changes',
        ),
        migrations.AddField(
            model_name='submenupricechange',
            name='form_item',
            field=models.ForeignKey(blank=True, help_text="The form item (e.g. 'NTinperson') this price change applies to.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu_price_changes', to='order_page.formitem'),
        ),
        migrations.AddField(
            model_name='submenupricechange',
            name='submenu_item',
            field=models.ForeignKey(blank=True, help_text="The submenu item (e.g. 'pages11_39', 'witness') this modifier applies to.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_modifiers', to='order_page.submenuitem'),
        ),
        migrations.AlterField(
            model_name='submenupricechange',
            name='change_type',
            field=models.CharField(choices=[('add', 'Add'), ('multiple', 'Multiple')], help_text='How this price modifies the base (additive or multiplier).', max_length=20),
        ),
        migrations.AlterField(
            model_name='submenupricechange',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The numeric amount or multiplier value.', max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='submenupricechange',
            name='key',
        ),
        migrations.AlterUniqueTogether(
            name='submenupricechange',
            unique_together={('form_item', 'submenu_item')},
        ),
    ]
