# Generated by Django 5.2.7 on 2025-11-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0014_alter_submenupricechange_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenu',
            old_name='label',
            new_name='name',
        ),
    ]
