# Generated by Django 5.2.7 on 2025-11-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0015_rename_label_submenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuitem',
            name='form_name',
            field=models.CharField(blank=True, help_text='Used in HTML form', max_length=255, null=True, verbose_name='Form Name'),
        ),
    ]
