# Generated by Django 5.2.7 on 2025-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0016_submenuitem_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuitem',
            name='type',
            field=models.CharField(blank=True, choices=[('radio', 'Radio'), ('counter', 'Counter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
