# Generated by Django 5.2.7 on 2025-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0017_alter_submenuitem_type_alter_submenuitem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaloption',
            name='valid_for_items',
            field=models.ManyToManyField(blank=True, help_text='Select the FormItems this modal option only applies to (Leave it blank to applied in all items).', related_name='modal_valid_options', to='order_page.formitem'),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='type',
            field=models.CharField(blank=True, choices=[('radio', 'Radio'), ('counter', 'Counter')], help_text='You cannot have Submenu type as Radio and Price modifier type as Multiple which breacks the order page', max_length=50, null=True),
        ),
    ]
