# Generated by Django 5.2.7 on 2025-11-18 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0018_modaloption_valid_for_items_alter_submenuitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleModalForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bundle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modal_form', to='order_page.bundle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleModalField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('radio', 'Radio'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('date', 'Date')], default='text', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default value')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='order_page.bundlemodalform')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('modal', 'name')},
            },
        ),
    ]
