# Generated by Django 5.2.7 on 2025-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0019_bundlemodalform_bundlemodalfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleoptionitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundleoptionitem',
            name='num_val',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundleoptionitem',
            name='text_val',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundleoptionitem',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('checkbox', 'Checkbox')], max_length=50, null=True),
        ),
    ]
