# Generated by Django 5.2.7 on 2025-11-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0020_bundleoptionitem_name_bundleoptionitem_num_val_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundlemodalfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bundlemodalform',
            name='bundle',
        ),
        migrations.AddField(
            model_name='bundle',
            name='modal_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle', to='order_page.bundlemodalform'),
        ),
        migrations.AddField(
            model_name='bundlemodalform',
            name='field',
            field=models.ManyToManyField(blank=True, null=True, related_name='form', to='order_page.bundlemodalfield'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='option_groups',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='order_page.bundleoptiongroup'),
        ),
        migrations.RemoveField(
            model_name='bundlemodalfield',
            name='modal',
        ),
    ]
