# Generated by Django 5.2.7 on 2025-11-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0021_alter_bundlemodalfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleoptionitem',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=50, null=True),
        ),
    ]
