# Generated by Django 5.2.7 on 2025-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0022_alter_bundleoptionitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundleoptiongroup',
            name='type',
        ),
    ]
