# Generated by Django 5.2.7 on 2025-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0023_remove_bundleoptiongroup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleoptiongroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
