# Generated by Django 5.2.7 on 2025-11-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0024_bundleoptiongroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundleoptionitem',
            old_name='price_add',
            new_name='price_change',
        ),
    ]
