# Generated by Django 5.2.7 on 2025-11-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0025_rename_price_add_bundleoptionitem_price_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaloption',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default value'),
        ),
    ]
