# Generated by Django 5.2.7 on 2025-11-24 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0026_modaloption_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.PositiveIntegerField(help_text='Minimum items required')),
                ('percent', models.DecimalField(decimal_places=2, help_text='Percentage discount', max_digits=5)),
                ('active_flag', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['items'],
                'unique_together': {('items', 'percent')},
            },
        ),
    ]
