# Generated by Django 5.2.7 on 2025-12-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0027_discountlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaloption',
            name='footer_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modaloption',
            name='footer_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
