# Generated by Django 5.2.7 on 2025-12-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0028_modaloption_footer_body_modaloption_footer_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofconditions',
            name='version_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
