# Generated by Django 5.2.7 on 2025-12-12 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0029_termsofconditions_version_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDiscloure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False, help_text='Is this disclosure required?')),
                ('message', models.TextField(help_text='Disclosure or information message to show')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active_flag', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='bundlemodalform',
            name='check_disclosure',
            field=models.ManyToManyField(blank=True, help_text='Select the disclosures to show in this ', related_name='modal_forms', to='order_page.checkdiscloure'),
        ),
        migrations.AddField(
            model_name='modaloption',
            name='check_disclosure',
            field=models.ManyToManyField(blank=True, help_text='Select the disclosures this modal option only applies to (Leave it blank to applied in all disclosures).', related_name='modal_options', to='order_page.checkdiscloure'),
        ),
    ]
