# Generated by Django 5.2.7 on 2025-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0030_checkdiscloure_bundlemodalform_check_disclosure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaloption',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
