# Generated by Django 5.2.7 on 2026-01-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0031_modaloption_hidden'),
        ('tolt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeformPartnerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_ref', models.CharField(help_text="The 'ref' of the choice in Typeform definition", max_length=100)),
                ('choice_label', models.CharField(help_text='The readable label of the choice', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_mappings', to='order_page.typeformfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_mappings', to='order_page.typeformform')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeform_mappings', to='tolt.partner')),
            ],
            options={
                'verbose_name': 'Typeform Partner Mapping',
                'verbose_name_plural': 'Typeform Partner Mappings',
                'unique_together': {('form', 'field', 'choice_ref')},
            },
        ),
    ]
