# Generated by Django 5.2.7 on 2026-01-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0032_typeformpartnermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeformform',
            name='cui_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='typeformform',
            name='hidden',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='typeformform',
            name='theme',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='typeformform',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='typeformform',
            name='workspace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TypeformLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logics', to='order_page.typeformform')),
            ],
        ),
        migrations.CreateModel(
            name='TypeformThankYouScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('attachment', models.JSONField(blank=True, default=dict)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thankyou_screens_models', to='order_page.typeformform')),
            ],
        ),
        migrations.CreateModel(
            name='TypeformWelcomeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('attachment', models.JSONField(blank=True, default=dict)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_screens', to='order_page.typeformform')),
            ],
        ),
    ]
