# Generated by Django 5.2.7 on 2026-01-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0033_typeformform_cui_settings_typeformform_hidden_and_more'),
        ('tolt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeformpartnermapping',
            name='choice_ref',
            field=models.CharField(blank=True, help_text="The 'ref' of the choice in Typeform definition", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='typeformpartnermapping',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeform_mappings', to='tolt.partner'),
        ),
    ]
