# Generated by Django 5.2.7 on 2026-01-22 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0034_alter_typeformpartnermapping_choice_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalOptionToggle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('toggle_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio')], default='checkbox', max_length=50)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for radio toggles (e.g. ["Yes", "No"]).', null=True)),
                ('trigger_value', models.CharField(help_text="Value that triggers the visibility of the field (e.g. 'true' or 'Yes').", max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('modal_option', models.ForeignKey(help_text='The parent modal option this toggle controls.', on_delete=django.db.models.deletion.CASCADE, related_name='toggles', to='order_page.modaloption')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
