# Generated by Django 5.2.11 on 2026-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0036_bundle_min_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='min_lead_time',
            field=models.SmallIntegerField(default=0, verbose_name='Minimum Lead Time (in hours)'),
        ),
    ]
