# Generated by Django 5.2.11 on 2026-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0039_framer_registration_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='discount_eligible',
            field=models.BooleanField(default=False, help_text="If True, selecting this item counts toward the order's stacking-discount tier count.", verbose_name='Counts Toward Stacking Discount'),
        ),
        migrations.AddField(
            model_name='formitem',
            name='discount_requires_option',
            field=models.BooleanField(default=False, help_text='If True, this item only counts toward the stacking discount when at least one of its options is also selected.', verbose_name='Discount Requires Option Selected'),
        ),
    ]
