# Generated by Django 5.2.11 on 2026-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0041_backfill_discount_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionitem',
            name='name',
            field=models.CharField(blank=True, help_text='Radio group key. Options sharing the same name (within the same item) are mutually exclusive when type=radio. Ignored for checkbox.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='optionitem',
            name='type',
            field=models.CharField(blank=True, choices=[('checkbox', 'Checkbox'), ('radio', 'Radio')], help_text='Selection behavior. Null/blank behaves as checkbox (independent, additive). Set to radio for options that should be mutually exclusive within their group (e.g. two priceChange options where only one should ever apply) -- pair with name.', max_length=10, null=True),
        ),
    ]
