# Generated by Django 5.2.11 on 2026-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_page', '0041_backfill_discount_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio')], default='checkbox', help_text='checkbox: items are independent. radio: items in this group are mutually exclusive -- use for priceChange-type options where only one should ever apply (selecting one clears the others).', max_length=50),
        ),
    ]
